### ISSUE TITLE
Forum Model not shows on admin site

### ISSUE THREAD

**Issue by Zhenyu-Liu** [ellmetha/django-machina#105]
I have an existing Django project works and I want to integrate machina into my project. After followed the step in the document I got this kind of error. Below is the traceback. 

```
[08/Feb/2018 19:39:57] "GET / HTTP/1.1" 200 7228
Internal Server Error: /forum/
Traceback (most recent call last):
  File "/Users/liuzhenyu/anaconda3/envs/sobertool/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/liuzhenyu/anaconda3/envs/sobertool/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuzhenyu/anaconda3/envs/sobertool/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/liuzhenyu/anaconda3/envs/sobertool/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/liuzhenyu/anaconda3/envs/sobertool/lib/python3.5/site-packages/django/views/generic/list.py", line 159, in get
    self.object_list = self.get_queryset()
  File "/Users/liuzhenyu/anaconda3/envs/sobertool/lib/python3.5/site-packages/machina/apps/forum/views.py", line 32, in get_queryset
    self.request.forum_permission_handler.forum_list_filter(
AttributeError: 'WSGIRequest' object has no attribute 'forum_permission_handler'
[08/Feb/2018 19:40:08] "GET /forum/ HTTP/1.1" 500 89067
```

Python version 3.5
Django version 1.9.5

**Comment by Zhenyu-Liu** [comment]
Hi @ellmetha Just now I tried to make a new python virtual environment and follow each step again, then I got the forum start correctly, everything works perfectly. I think the problem is from the version of Django or the package that I use is not match (Django 2.0 changes the url cause some of my packages does not work well). But one problem I found is that I cannot find the Forum in my administration site so that I cannot add a post to the forum. Did I miss some setting?  Thank you so much!

**Comment by Zhenyu-Liu** [comment]
Any thoughts about the cause of models not shown on admin site?

**Comment by ellmetha** [comment]
@Zhenyu-Liu no. It is probably related to your project's settings. Difficult to tell without additional information but my first guess is that the installation procedure was not properly followed. 😉

**Comment by ellmetha** [comment]
Closing due to lack of activity.
