### ISSUE TITLE
ImproperlyConfigured error, but it is configured properly

### ISSUE THREAD

**Issue by DiscoMushroom** [ellmetha/django-machina#148]
# Hi

I installed the newest version of django-machina on my local development server yesterday. I customized it to work the way I want and it works perfectly.

In my **settings.py** is the following as required. Note that 2 caches are used. The first for the site, and the 2nd for the forum which requires **FileBasedCache**. I made the `/tmp/django_machina_forum` directory too. So it exists.

    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': '127.0.0.1:11211',
        },
        'machina_attachments': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': '/tmp/django_machina_forum',
        },
    }

When I try to put this on the vps for the same project, after going through the documentation again, installing the proper **settings.py**, `pip install django-machina` and all it's requirements, I'm getting this error after I `python manage.py makemigrations`:

    django.core.exceptions.ImproperlyConfigured: The attachment cache backend (machina_attachments) is not configured

As you can see, `'machina_attachments'` is properly configured. To try and debug this, I went to `machina.conf.settings` and `machina.apps.forum_conversation.forum_attachments.cache` to make sure their imports weren't messed up. In the **cache.py** file we have:

    def get_backend(self):
            try:
                cache = caches[machina_settings.ATTACHMENT_CACHE_NAME]
            except InvalidCacheBackendError:
                raise ImproperlyConfigured(
                    'The attachment cache backend ({}) is not configured'.format(
                        machina_settings.ATTACHMENT_CACHE_NAME))
            return cache

So I go to the settings file they imported here *(which is `machina_settings`)*, and I find `ATTACHMENT_CACHE_NAME = getattr(settings, 'MACHINA_ATTACHMENT_CACHE_NAME', 'machina_attachments')`. At the top it says it's `from django.conf import settings`...

**So does anyone have any idea what is wrong here??**

The documentation says the setting is defaulted to `'machina_attachments'`, but as you can see above, it is, but it's not working...

Any help is appreciated.

## Here's the full traceback:

    Traceback (most recent call last):
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/apps/forum_conversation/forum_attachments/cache.py", line 32, in get_backend
        cache = caches[machina_settings.ATTACHMENT_CACHE_NAME]
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
        "Could not find config for '%s' in settings.CACHES" % alias
    django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'machina_attachments' in settings.CACHES
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "manage.py", line 15, in <module>
        execute_from_command_line(sys.argv)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
        utility.execute()
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/management/base.py", line 332, in execute
        self.check()
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
        include_deployment_checks=include_deployment_checks,
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
        return checks.run_checks(**kwargs)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
        all_namespaces = _load_all_namespaces(resolver)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
        url_patterns = getattr(resolver, 'url_patterns', [])
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
        return import_module(self.urlconf_name)
      File "/home/djangodeploy/myvenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/home/djangodeploy/portfolio-project/pwnsaucedesigns/urls.py", line 26, in <module>
        from machina.app import board
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/app.py", line 22, in <module>
        class BoardApp(Application):
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/app.py", line 28, in BoardApp
        conversation_app = get_class('forum_conversation.app', 'application')
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 20, in get_class
        return get_classes(module_label, [classname, ])[0]
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 47, in get_classes
        local_imported_module = _import_module(module_path, classnames)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 70, in _import_module
        imported_module = __import__(module_path, fromlist=classnames)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/apps/forum_conversation/app.py", line 15, in <module>
        class BaseConversationApp(Application):
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/apps/forum_conversation/app.py", line 18, in BaseConversationApp
        topic_view = get_class('forum_conversation.views', 'TopicView')
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 20, in get_class
        return get_classes(module_label, [classname, ])[0]
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 47, in get_classes
        local_imported_module = _import_module(module_path, classnames)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 70, in _import_module
        imported_module = __import__(module_path, fromlist=classnames)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/apps/forum_conversation/views.py", line 35, in <module>
        attachments_cache = get_class('forum_attachments.cache', 'cache')
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 20, in get_class
        return get_classes(module_label, [classname, ])[0]
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 47, in get_classes
        local_imported_module = _import_module(module_path, classnames)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/core/loading.py", line 70, in _import_module
        imported_module = __import__(module_path, fromlist=classnames)
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/apps/forum_conversation/forum_attachments/cache.py", line 119, in <module>
        cache = AttachmentCache()
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/apps/forum_conversation/forum_attachments/cache.py", line 28, in __init__
        self.backend = self.get_backend()
      File "/home/djangodeploy/myvenv/lib/python3.5/site-packages/machina/apps/forum_conversation/forum_attachments/cache.py", line 36, in get_backend
        machina_settings.ATTACHMENT_CACHE_NAME))
    django.core.exceptions.ImproperlyConfigured: The attachment cache backend (machina_attachments) is not configured

**Comment by ellmetha** [comment]
Well your `CACHES` setting doesn't seem to be the one used by your Django project. Perhaps you're using dev-specific settings that override the default `CACHES` value? You could easily check the content of your `CACHES` setting by running something like: `python manage.py shell -c 'from django.conf import settings ; print(settings.CACHES)'`.

**Comment by DiscoMushroom** [comment]
# me.giant_facepalm(activate=True)

I forgot I had a local development settings, and a production one. 

It wasn't in there.

Problems fixed!

Thanks!

**Comment by danlanko** [comment]
> # me.giant_facepalm(activate=True)
> 
> I forgot I had a local development settings, and a production one.
> 
> It wasn't in there.
> 
> Problems fixed!
> 
> Thanks!

Problem Fixed.... But you cannot state how you fixed the problem to help someone else that might be struggling with similar issues....

**Comment by PwnSauceDesigns** [comment]
No need for the attitude.

And the description was in my words: I had 2 setings.py files. One was for the development server, the other was for production _(the one online)._

The production_settings.py in the online version was older, so it was overwriting the new value I put in the development_settings.py. Making it so the new settings weren't recognized.

So all I did was copy/paste the correct value from development_settings.py to production_settings.py, and it was fine after restarting the wsgi.
