### ISSUE TITLE
App override gets django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: forum_permission

### ISSUE THREAD

**Issue by vaughnd** [ellmetha/django-machina#278]
Django 4.0.6

I followed the docs at https://django-machina.readthedocs.io/en/stable/customization/overriding_applications.html to override the forum_permission app, but I get this error. I can't set a different label because then the dynamic class loading in get_model(app_label, model_name) will fail. Not sure how to get around this.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vaughn/.local/share/virtualenvs/psnplatform-I1NAM19a/lib/python3.10/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: forum_permission
```

**Comment by vaughnd** [comment]
I missed the part about _replacing_ the base app in settings.py. Sorry!
