### ISSUE TITLE
Cant get to work: "ImportError: No module named board.urls"

### ISSUE THREAD

**Issue by iDemiurgeCHS** [ellmetha/django-machina#61]
I am probably missing somthing basic. 
I have machina installed and followed the instructions to the T.
Unhandled exception in thread started by <function wrapper at 0x7fd3758700c8>

> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nick/Desktop/django stuff/clubotaku/clubotaku/urls.py", line 22, in <module>
    url(r'^forum/', include('board.urls')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named board.urls

and here is my urls.py -

 from django.conf.urls import url, include
from django.contrib import admin
from machina.app import board
urlpatterns = [
	url(r'^$', include('home.urls')),
	url(r'^anime/', include('anime.urls')),
	url(r'^forum/', include('board.urls')),
	url(r'^shop', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
]

please help i dont know what im missing lol. probably something simple tbh cx

**Comment by iDemiurgeCHS** [comment]
Problem solved!
It was the settings and having app URL set true.

**Comment by cmlizama** [comment]
@iDemiurgeCHS Hello. I know this issue is closed, but I am having the same problem and I was wondering if I could get more detail as to how you fixed it. Thanks so much.
