### ISSUE TITLE
docker-compose build vanilla

### ISSUE THREAD

**Issue by kixiro** [ellmetha/django-machina#76]
I'm run ```docker-compose build vanilla``` and get Failed:

<pre>
Removing intermediate container ef5b4ca47ace
Step 12/13 : RUN python $ppath/manage.py createsuperuser --username=admin --email=test@example.com --noinput
 ---> Running in 7ff0a6643439
Superuser created successfully.
 ---> 3ad43396a549
Removing intermediate container 7ff0a6643439
Step 13/13 : RUN python $ppath/manage.py loaddata $fixturepath/*
 ---> Running in 4a51830eaa4f
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/models/options.py", line 617, in get_field
    return self.fields_map[field_name]
KeyError: 'posts_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/local/lib/python3.5/site-packages/django/core/serializers/python.py", line 129, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Forum has no field named 'posts_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/example_projects/vanilla/manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 166, in load_label
    for obj in objects:
  File "/usr/local/lib/python3.5/site-packages/django/core/serializers/json.py", line 88, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/local/lib/python3.5/site-packages/django/core/serializers/python.py", line 129, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.serializers.base.DeserializationError: Problem installing fixture '/opt/code/example_projects/vanilla/vanilla_project/fixtures/forums.json': Forum has no field named 'posts_count'
ERROR: Service 'vanilla' failed to build: The command '/bin/sh -c python $ppath/manage.py loaddata $fixturepath/*' returned a non-zero code: 1
</pre>

<pre>
 # docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
</pre>
<pre>
# docker-compose -version
docker-compose version 1.14.0, build c7bdf9e
</pre>
What is the problem?

**Comment by ellmetha** [comment]
Thanks for reporting this. 😉 The problem has been fixed in 069d455.
