### ISSUE TITLE
Error when triying to disaprove a post

### ISSUE THREAD

**Issue by synw** [ellmetha/django-machina#9]
Occurs when I click on the Yes button for disapproving a post.

Internal Server Error: /forum/moderation/queue/1/disapprove/
Traceback (most recent call last):
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/machina/apps/forum_permission/viewmixins.py", line 109, in dispatch
    return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/machina/apps/forum_moderation/views.py", line 453, in post
    return self.disapprove(request, *args, **kwargs)
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/machina/apps/forum_moderation/views.py", line 449, in disapprove
    self.object.delete()
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/machina/apps/forum_conversation/abstract_models.py", line 297, in delete
    if self.is_topic_head and self.is_topic_tail:
  File "/home/me/www/my_project/local/lib/python2.7/site-packages/machina/apps/forum_conversation/abstract_models.py", line 259, in is_topic_tail
    return self.topic.last_post.id == self.id
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by synw** [comment]
Same error appears when I try to delete the post via the admin. But admin delete works if the post is approved.

**Comment by ellmetha** [comment]
Hi,
Thanks for reporting this! This should be fixed with 2192384. ;)
